CC=gcc
CFLAGS=-g
.PHONY: all run clean

all:patwa_shubham_pa3_floyd.c patwa_shubham_pa3_lcs.c
	$(CC) $(CFLAGS) patwa_shubham_pa3_floyd.c -o floyd
	$(CC) $(CFLAGS) patwa_shubham_pa3_lcs.c -o lcs
	

clean: 
	rm floyd
	rm lcs



        


